[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "80d53b02527e243dc717460c24a35e7dbb0e0984"
os = "macos"

    [[libcellml.download]]
    sha256 = "50e808aeaf27763158067460dd63559c65057256b4608a254c1961e42c3b8d85"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.aarch64-apple-darwin.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4070a324128ae0ea84ad59ec1cdfccbb467b63ce"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "6139b614f677b18939be9a4f2199bf0001d482c7df412f7ebf7931f2a0fdcd56"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dceb39972bfd71f84e89a8de3bbdec5e5166db17"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "48cbbf7fb51defc91468c5a7be7f42d086e121b42510d038091479a364280e64"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.aarch64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "6f16cf348b9be13ab73a16250b4c4b9da557f851"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "2115c68901ba7403408338f013113bc25a4c82a43871ae75fe5fb3af5a2d3ea0"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.aarch64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16c33aaa5ff9c46526aa88b7280cd1de2cf0cca1"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "566c304ad5e41e5913c9b108359a7c8bffe3e37df78c7d5770046b24095d439d"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be0d27ee9295cc0e85e52225003a3bcf2bc843ae"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "266b482cf0f05834748320707b867f0828c977bfb592f3756ea1815299b69281"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.riscv64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "0a12aea42e5e158ae15fe1aaedda0d554566f2de"
os = "macos"

    [[libcellml.download]]
    sha256 = "aaca9049ed57f4117b0366abca7d3d668845ebf0f25c8c1e0e19d051129c8eb5"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.x86_64-apple-darwin.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b22569b83ec6226f357a32d172bd39b59811f8b"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "5d0da85c09b1476401a173c62b93a75be802856205a3e332f17f32c598296fcf"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4bf82abe7581d9e437b1fe76d51a236d8bfc2df5"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "25c0e4ac4d95ba5fb0630215552f507e8a1c129921b62ecb900059ed70545355"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.x86_64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "ea1dcdd96714a13e358cad3b865947f95fbb6024"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "45a4c38bbfe5bd44c4039540629de2da3c7eab5f4c5559b4cb6908fd9bdb0418"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.x86_64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2440e6daf549a0094f4f6dca639f6fea0911b6b4"
os = "windows"

    [[libcellml.download]]
    sha256 = "cc94497fc885678d046efd8db52eef9ba9bd85bbe460031d6d7230f365654c25"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.1+0/libcellml.v0.7.1.x86_64-w64-mingw32-cxx11.tar.gz"
