[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "0d5daefce0024a7daff02cf20684df91e2eef3af"
os = "macos"

    [[libcellml.download]]
    sha256 = "d511dc6e64e87248d15e6cde597af1f9438ef96be8fe0ae1e748b02c60f85e07"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.aarch64-apple-darwin.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "44d3b442514228ba608735de7197d55e604acef8"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "c0819f46eebdb13498dc1e7df71faa8678947a46d9f2f96d3310e0d83f0cdf41"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.aarch64-linux-gnu-cxx03.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47aa355a0600f2399fc9ef1779ffada55d031a3b"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "5179bd4f7e39a0a6912c73ef1e1d9b8ac94ef4934b53c288b03de07c1cbc24ec"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.aarch64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d808606bd537f693c7a934e85f70a79fb12ee2c1"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "98bed6cf0b875cb5a02868d6cddfab0eaa245ec4d0d4eb26bed94b684164f239"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.aarch64-linux-musl-cxx03.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89c0640f858683e1350b5f104c2f604028a22b5b"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "3379bf052e4835c714aa19e24162da3ccc0d1814ca5709bf12682f86efec9312"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.aarch64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "38a3d0f0b3bedde3ffbbd93db481c03bbf431a59"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "466d16ff8a1612695c96223b6ce69367a211569193da71ab979ca9ef687ab0f4"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.aarch64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4d29823c314fc1a4f439a26f36f2711272f5ced"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "2afa79bff1d9d2f20b024ac91fa4d7376230b7e4c9e26e23a30cfd679dd84732"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcellml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c7849842802f5e3f6ecd983d0bafc90e97a9c95"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "37a61b746958a4e633af0da810ef485c40166bdaa2451cef1deca6f136b68c99"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "d9ba9cf48beb66de94f13823eeedf67de439a092"
os = "macos"

    [[libcellml.download]]
    sha256 = "1ae9d5edb6555712a27d6267f48499b3e95169e7aaa7f29be59916af01f99fcb"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-apple-darwin.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a78e9dd0d12acadfcbb738bd6c51c7ac183040dd"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "20f1b9753c0b9797130ee80db1ab61f36d3e1f8c26c4771d375c88f8ee3aaae9"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-linux-gnu-cxx03.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "379f42781e26db838f92f73e95145e77ae204f4e"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "7eb8639a133c03dbe0652010f7a694eb598134fd6e02c781c80aa01daefab302"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89704b2f366b042df7106a592103bb5fdfb5c743"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "36798de17f4eacb44cbd7b357df0673157b53445c03a427570febbfc028c1f23"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-linux-musl-cxx03.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "986182a8f7df2c980bf1afa9aa6a8e7961ceeacf"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "9113ae72f0f9a0a8f005b921def27ee94d2eda65c953c532a583990f8a68c1f9"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "f5c78ae27474691b1fb41e0986c78692832a9681"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "4d13974ffa61a5c983af79f1ae0dfbb730d9876de96d7e89081d034bf0718bb3"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43c99b8cd8e1d26c0351b15ba2f67102887438fd"
os = "windows"

    [[libcellml.download]]
    sha256 = "1bcd54f160ce7bc0199170bef7549701986c107e60645247f5c0845f87cf4d5a"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "077256102b9082a82ad683dd17b2c95535ef6327"
os = "windows"

    [[libcellml.download]]
    sha256 = "cdfd320e83de56f4cc59d65b6337570865a8b4d5178f5b20e37ecf1b07d9d940"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.2+0/libcellml.v0.6.2.x86_64-w64-mingw32-cxx11.tar.gz"
