[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "491551c4c0d9fccd1d0105c93ad847180a75ba2e"
os = "macos"

    [[libcellml.download]]
    sha256 = "d05beffd9d0205a4592784e277506ca6f02ee15e7d1487d7f203929357033f8d"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.aarch64-apple-darwin.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22702850869ede253d5d787e38666e4c1462d8d3"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "04128fcdf636af28fd1054f822f02ae87da8cf06e51f9e8dae7b91d7b10a6e00"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7225eaf4f21a4f5e485be0c18704e5148b1c74a"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "8ce485e5a224a8e04bf8a294fa0da72d2d3ddb9c4493f26ecfe87eee1e9ceae3"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "ee1ea1ca90e29ca91daa47c8190906f7dd332d8b"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "9012bcd38e72a16ba06dbb95e375c74e821f6a073a2c5eb65713c7d23729a1e8"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.aarch64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40c64f19ba83b936f2aba7841df46422565a518d"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "61de3067ac9bf863baa72c2459c1a680ff3bd29549e52e0e7ef8202aa7972e8a"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98f4ea88f307da7ad56efc3edb4e0ffe28660b59"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "3f0c6284d366e98bca025e5b02603e84999b49db335549f55e2361c43983056e"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.riscv64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "dbaae04fcfa25f4d3f2ce7ad219ad22dc609c33c"
os = "macos"

    [[libcellml.download]]
    sha256 = "515a169ff2265f1e607e37764d7ca46d9f861b46e997d53e1fff75ddbcf06b38"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.x86_64-apple-darwin.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef2bdf54f17f9993ecb466e76e50eb2a02fee19a"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "424ed8e81a5d58d84b883f81d1b3ce5cbf7f4a782a28ea5b8da4029c9a069249"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f796a10035336efa4cb59c68f9f906ff6fa6850c"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "5a29546190b77b2855300e5bffe5ef036abec9a1db8d4919b2f7f7e9e3b6b9da"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "dcad0665525099236faac1ea19bb3c16024adf08"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "ec00cf206907682a097e18c83f2dbd5067616dd103261d049465a10a45d0eb48"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.x86_64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1082ead93e039e2d9e6c6d1e0b587542e2778d57"
os = "windows"

    [[libcellml.download]]
    sha256 = "6b95d72c58bc8503c0f93fe6e28b91f5b83934ad40f5604803e5094f8b1a741e"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.7.0+0/libcellml.v0.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
