[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "a816588e801c71a0ae0c2ce22962bd1f597f4d31"
os = "macos"

    [[libcellml.download]]
    sha256 = "c34e289ee79288cdcefc34eabeba741dc71230d9a71e643cc711c4d8bd4844b5"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.aarch64-apple-darwin.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9819a28fb4945fde87df4bb7251c95e5196345a5"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "acb7c04a8ac04913b61b71a7867443cf17453fe9a4d184c7a681cb4c4eadab3c"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aff4e5318cb7b63864ba31528a142b1b659aae81"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "1c514b18ad69832020e3332f22f7b884f1184d04c63bf2e3be80226346459273"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80d04a95abe987e6178fcb573692b36a74e25ab7"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "629e2f3f7cd7f7eb62d2c82a2e0820bdbe18903892b944e5acd92be23484248e"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.aarch64-linux-musl-cxx03.tar.gz"
[[libcellml]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "931058830bbdb4864d643e404ba71b76c0dbc151"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "3260a17839fd5260f45eefa93c7206363aeed9dd01e125ebc339dac4fc84a578"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.aarch64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "aarch64"
git-tree-sha1 = "fa0a72d49a331bb8eed3aa83c131e08d0768da28"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "31c361841cc847bd4d2490c3a0c59e2880a1e2a92b7677d21f5a580048279460"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.aarch64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cbc725776a4572672353d6d45ce7235f7d08cac"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "529ee463942208cd9c362f93394945beb0322647851d39c62fe4bab1f42da872"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcellml]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63b916167c6904d4b07d91ad898a555c94472a35"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "144a89155cb7f6dd3f606fb9fe9fdad454c66fa46086ecd414292f474ed2e8bc"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "68fcc995742afa70f73e829cb7f4c379265090ef"
os = "macos"

    [[libcellml.download]]
    sha256 = "7e88c77b97c4883c5cfed4210647d9ca7b20f188325ec9d517c594ac9aa0d838"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-apple-darwin.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95d335cb46c3bd594ad969c49578f9a504efcfc0"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "f7a757139ccd1b7f178ddcd2fa378faada171cf4f571fb9edbafa42ab3f63021"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b20285acd36a4d0de017e3790fae6c3a1bf7f91"
libc = "glibc"
os = "linux"

    [[libcellml.download]]
    sha256 = "1f08047a5c9715c3ee504b2d6a36e2d9453ce1718850f0ae50863bf350754cf4"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aacf2047efbb8f94c80ac416d52debab8e375b6b"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "c63ca87a5b78be414424dd63c78096d5da0bae6fd32d462ae062a07d8e3593da"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-linux-musl-cxx03.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "175f9cd33c26aad6ba69a4ed7a9fc271fa0f942d"
libc = "musl"
os = "linux"

    [[libcellml.download]]
    sha256 = "5f57bb7ddd3294246065640d9a799830be1f2813826bf4dba32510d91b29cdc0"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-linux-musl-cxx11.tar.gz"
[[libcellml]]
arch = "x86_64"
git-tree-sha1 = "f2d82b790724bc22866f9c9f00c0fe5afd6c8861"
os = "freebsd"

    [[libcellml.download]]
    sha256 = "8a560c71ae2bd70ea00d45c576a6b8d0f75eb8bbe2c18ed432d07a7b4b435552"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-unknown-freebsd.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfe5d0e4549a7970813aaeeb3a2600d03a1fe92c"
os = "windows"

    [[libcellml.download]]
    sha256 = "addc9b7544e1064c61221177c63a76eb8283b05d3ee4c0a6216ef7731e1db2da"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcellml]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2d7ceb11c18ae49d77fb54390d1271150931c29"
os = "windows"

    [[libcellml.download]]
    sha256 = "6d493a038447af352f135430c55b7cf29cccf14dd8260bf4320353629521b03e"
    url = "https://github.com/JuliaBinaryWrappers/libcellml_jll.jl/releases/download/libcellml-v0.6.3+0/libcellml.v0.6.3.x86_64-w64-mingw32-cxx11.tar.gz"
