# Autogenerated wrapper script for libcellml_jll for aarch64-apple-darwin
export libcellml

using XML2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libcellml")
JLLWrappers.@declare_library_product(libcellml, "@rpath/libcellml.0.6.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libcellml,
        "lib/libcellml.0.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
