# Autogenerated wrapper script for libcellml_jll for x86_64-w64-mingw32-cxx11
export libcellml

using XML2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libcellml")
JLLWrappers.@declare_library_product(libcellml, "libcellml.dll")
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libcellml,
        "bin\\libcellml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
